@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@baseUrl = rickandmorty
@contentType = application/json
@url = login

###
POST http://{{host}}/{{baseUrl}}/{{url}}
Content-Type: application/json

{
    "email": "nicosalvo@gmail.com",
    "password": ""
}

###
GET http://{{host}}/{{baseUrl}}/{{url}}
Content-Type: application/json

{
    "email": "nicosalvo@gmail.com",
    "password": ""
}

###
GET http://{{host}}/{{baseUrl}}/{{url}}
Content-Type: application/json

{
    "email": "sarasa@gmail.com",
    "password": ""
}
