@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@baseUrl = rickandmorty
@contentType = application/json
@url = fav

###
POST http://{{host}}/{{baseUrl}}/{{url}}
Content-Type: application/json

{
    "id": 1,
    "name": "El uno",
    "gender": "Male",
    "species": "Human",
    "origin": {"name": "Earth"},
    "image": "someImagePath",
    "status": "Alive"
}

###
DELETE  http://{{host}}/{{baseUrl}}/{{url}}/1
